version: '3'
services:
  frontend:
    container_name: "sonar-frontend"
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/usr/src/app/src
    links:
      - backend
  backend:
    container_name: "sonar-backend"
    build: ./server
    restart: always
    ports:
      - "5500:5500"
      - "9229:9229"
    volumes:
      - ./server/app:/usr/src/app/app
    links:
      - mongo
      - redis
  mongo:
    container_name: "sonar-mongo"
    image: mongo
    volumes:
      - ./data/db/mongo:/data/db
    ports:
      - "27017:27017"
  redis:
    container_name: "sonar-redis"
    image: redis
    ports:
      - "6379:6379"
